set nu
set mouse=nv
set report=0
set nowrap
set nobackup
set nowritebackup
set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
set termguicolors
set hidden
set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=yes
let mapleader=";"
